### PR TITLE
BF-Math-Normalizers: Update parameters of Z-transofrmer with a replaced element

### LINKED ISSUE #478: BF-Math: Update parameters on deleted Instances for Z transformer
**New method update_parameters_del() that updates the parameters of z-transformer when obsolete data is removed from the dataset (window)**
...

**Task list**
- [x] 1. New method _update_parameters_del()
- [x] 2. rename method _update_parmeters() to _update_parameters_new()
- [x] 3. class diagram and howto modifications

**Task List (Redefined)**
- [x] 1. Method _update_parameters() takes 3 arguments, if prvided p_data_del, then the parameters are updated based on replacement otherwise normally
- [x] 2. update class diagram
- [x] 3. update how to

**Related issues**
#...

**Cross references**
...

### PR DESCRIPTION
**Pull request by laxmikantbaheti**
Update the parameters with an element that replaces an old element

## Description
In a stream scenario with windows, after the buffer is full, a new element replaces an old element. The parameters of the normalizer shall be updated for the same

## Background
Closes #478 

## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti can I review this?The related issue is set to done.

**Comment by laxmikantbaheti** [comment]
> Hi @laxmikantbaheti can I review this?The related issue is set to done.

Hi @detlefarend , yes, I just requested a review. Thanks!

**Comment by detlefarend** [comment]
> > Hi @laxmikantbaheti can I review this?The related issue is set to done.
> 
> Hi @detlefarend , yes, I just requested a review. Thanks!

Ok, I'll take a look. The pr is still a 'draft'. That's why I didn't review it until now. There is this button 'Ready for review'. Please press to change the pr type. Thx!

**Review by detlefarend — COMMENTED** [review]
Hi @laxmikantbaheti, the code of the normalizers is very clean. I wonder why the z-tranformer doesn't scale to [-1,1]:

grafik

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , the z-transform does not normalize data into defined boundaries. Instead, it standardizes a dataset to a mean of 0 and standard deviation of 1. This is useful if you have distributions from different domains, and want to compare them with a common score.

**Comment by detlefarend** [comment]
> Hi @detlefarend , the z-transform does not normalize data into defined boundaries. Instead, it standardizes a dataset to a mean of 0 and standard deviation of 1. This is useful if you have distributions from different domains, and want to compare them with a common score. So, in case of z-transform normalization ( or standardization ) the value need not be within -1 to 1.

I obviously had a misconception... Good job!

**Pull request merged**
