### PR TITLE
Model Improvements 8

### PR DESCRIPTION
**Pull request by detlefarend**
## Types of changes

- [ ] Bug fix
- [ ] New Example, please read the detailed guideline [here](https://www.google.com)
- [x] New Feature
- [ ] Documentation

## New Feature

- [x] Model (Improvement on the Core Model)
- [ ] Environment (New Environment), please read the detailed guideline [here](https://www.google.com)
- [ ] Policy (New Policy), please read the detailed guideline [here](https://www.google.com)
- [ ] .....

## Checklist:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide.
- [ ] Update the history on the source code (**required**).
- [ ] This change requires a change to the documentation.
- [ ] Update the tests accordingly.
- [ ] Update the documentation accordingly.

### CODE REVIEW

**Comment by detlefarend** [comment]
Hi @rizkydiprasetya, I just added an implementation for model based training inside class Agent. It's not yet tested but maybe interesting or worth to discuss anyway. Core concept is to start a training run to adapt the policy on the internal env model. I guess you implemented something similar in your MBRL scenario so that we can benefit from your experiences here. 

The extension includes:

- New class RLScenarioMBInt (for internal use in class Agent)
- Class Agent: new parameter p_mb_training_param
- Class Agent, constructor: setup of internal dictionary self._mb_training_param 
- Class Agent: implementation of method _adapt_policy_by_model()

**Comment by rizkydiprasetya** [comment]
@detlefarend please check, I just made some temporary changes, maybe you can change something on it. The Howto 16 is now running.

**Comment by detlefarend** [comment]
> @detlefarend please check, I just made some temporary changes, maybe you can change something on it. The Howto 16 is now running.

Looks good!

**Comment by detlefarend** [comment]
@rizkydiprasetya One question regarding AFct ./sl/pool/aft/afctrans_mlp_robotinhtm.py: it seems that it is branded to the robothtm sub-project. If so: shall we unite the related code in a new folder robothtm under rl/pool/envs? Or is the afct implementation itself universal/reusable?

**Comment by rizkydiprasetya** [comment]
Yes, it is branded to robothtm, because it only works for robothtm. Currently, it is not reusable. I am still working on the universal implementation for MLP afctrans.

**Comment by rizkydiprasetya** [comment]
I have added a universal afct implementation for neural network based on PyTorch.

**Pull request merged**
