### PR TITLE
BF-Adaptive Systems

### PR DESCRIPTION
**Pull request by laxmikantbaheti**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by laxmikantbaheti** [comment]
Hi @steveyuwono , @detlefarend , 
I think this branch has a lot of changes that need to be updated with the rest of the branches as well, so I propose to merge it to main once. Because:
1. After introducing the Demo Scenario I have introduces the new howto for the same and changed the numbers of previous howtos on systems. Consequently, I had to update the test list for howtos. 
2. Also, a critical change you might want to know is the new State - Instance relationship:
   - The state now inherits from the Instance object, and thus all the methods of the instance are possible to be used on the state as well.
   - The feature data of the instance references to the state itself. 
   - The set_feature_data and get_feature_data are overriden at this level.
 3. Other important change than that is:
    - Introduction of Demo Sceanrio and related howtos
    
 All the howots are running, and the tests are also running fine. A signal for merging would be cool. Thank you in advance!

**Comment by laxmikantbaheti** [comment]
Please ignore the changes at BF-ML-Systems and BF-OA-Systems for this pull request.

Also, I'd prefer changing the name of the pull request before merging: "BF-Systems-DemoScenario"

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, I think we should briefely discuss this - maybe tonight/tomorrow.

One thing in advance: you inherit State from Instance and Element. The feature data are stored in the Element part of State and not in _feature_data. I recommend to the opposite: redefining the Element methods so that they get/set the data from _feature_data.

def get_values():
   return self._feature_data.get_values()

def set_values():
   self._feature_data.set_values()

...

This way we can be sure, that the state itself is stored in the feature data element.

**Comment by laxmikantbaheti** [comment]
> Hi @laxmikantbaheti, I think we should briefely discuss this - maybe tonight/tomorrow.
> 
> One thing in advance: you inherit State from Instance and Element. The feature data are stored in the Element part of State and not in _feature_data. I recommend to the opposite: redefining the Element methods so that they get/set the data from _feature_data.
> 
> def get_values(): return self._feature_data.get_values()
> 
> def set_values(): self._feature_data.set_values()
> 
> ...
> 
> This way we can be sure, that the state itself is stored in the feature data element.

That also would work.

> Hi @laxmikantbaheti, I think we should briefely discuss this - maybe tonight/tomorrow.
> 
> One thing in advance: you inherit State from Instance and Element. The feature data are stored in the Element part of State and not in _feature_data. I recommend to the opposite: redefining the Element methods so that they get/set the data from _feature_data.
> 
> def get_values(): return self._feature_data.get_values()
> 
> def set_values(): self._feature_data.set_values()
> 
> ...
> 
> This way we can be sure, that the state itself is stored in the feature data element.

This would work too. I did the current implementation in order to not overwrite the methods from Element. But, now I think, there is a less chance of changes at element object than changes in the instance object. Besides, it is more like Instance then.
Agreed. I'll do.

**Review by detlefarend — APPROVED** [review]

**Pull request merged**
