### PR TITLE
Action Planner using MPC

### PR DESCRIPTION
**Pull request by steveyuwono**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by steveyuwono** [comment]
Hi @detlefarend,

I could find time today to implement MPC as a default implementation of the action planner. I have replaced the terminology of _depth_limit with _prediction_horizon. I also introduced a parameter called _control_horizon. These terminologies are taken from the MPC but they are applicable to action planners in general. I have a question, do we use the action planner only if the maturity of the env model is higher than the defined threshold? If yes, I believe these lines must be updated. https://github.com/fhswf/MLPro/blob/8375b7d33f88fee62e0d84d2a651e9e649ea8d54/src/mlpro/rl/models_agents.py#L680-L686

I updated howto 13 RL as well by adding the action planner functionality and now it is showing no errors. For further discussions and review, maybe we can do this together on Friday. Thank you and have a nice day!

**Comment by detlefarend** [comment]
Hi @steveyuwono, the planning itself is custom and not further standardized. Whether or not the maturity of the env model is taken into account is up to the specific implementation. But maybe we can go further and standardize this. If the maturity is below the threshold then we don't use the model. On the other hand, if the model is not suitable then the policy is not trained. It's an interesting dynamics. Let's talk about it on Friday. See you soon:)

**Comment by rizkydiprasetya** [comment]
@steveyuwono @detlefarend question here, do you take only the first action or the whole actions?

**Comment by steveyuwono** [comment]
@rizkydiprasetya the user can choose the control horizon. We introduce a variable, called _control_horizon. It can be in between 1 action and the prediction horizon.

**Pull request merged**
