### PR TITLE
RTD Updates

### PR DESCRIPTION
**Pull request by detlefarend**
## Types of changes

- [ ] Bug fix
- [ ] New Example, please read the detailed guideline [here](https://www.google.com)
- [ ] New Feature
- [x] Documentation

## New Feature

- [ ] Model (Improvement on the Core Model)
- [ ] Environment (New Environment), please read the detailed guideline [here](https://www.google.com)
- [ ] Policy (New Policy), please read the detailed guideline [here](https://www.google.com)
- [ ] .....

## Checklist:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide.
- [ ] Update the history on the source code (**required**).
- [ ] This change requires a change to the documentation.
- [ ] Update the tests accordingly.
- [ ] Update the documentation accordingly.

### CODE REVIEW

**Comment by rizkydiprasetya** [comment]
@detlefarend the RTD for envmodel is not there yet, should I put it there?

**Comment by detlefarend** [comment]
> @detlefarend the RTD for envmodel is not there yet, should I put it there?

Would be great! Maybe with a link to the related API section.

**Comment by detlefarend** [comment]
@budiatmadjajaWill: I checked the ur5 env doc and assigned the layout to our howto files. Especially I changed the headings. Cross reference and content is fine. I am not sure about the section "Version structure". The current version is shown on the API description. A technical change log is part of the source code. Hmmm, what about a section "Change log" and a table with two columns: Version of env, changes.

**Comment by budiatmadjajaWill** [comment]
Yes, that could work as well.

At least the user will have an idea when this documentation is created.

**Pull request merged**
