### PR TITLE
Installation option for mlpro "full"

### PR DESCRIPTION
**Pull request by rizkydiprasetya**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by rizkydiprasetya** [comment]
This is done. Ignore the checks. The actual checks can be seen on #580

**Comment by detlefarend** [comment]
> This is done. Ignore the checks. The actual checks can be seen on #580

I see.

**Review by detlefarend — APPROVED** [review]
Hi @rizkydiprasetya, looks good so far. I just tested the local installation using ./src/setup.py. I fixed a typo and after that the installation procedure worked well.

One question: does Anaconda also enable installation options?

Next question: should we provide two options
- "full_stable" with versioned depending packages
- "full_latest" with latest versions of depending packages

The latter one helps us MLPro developers to validate on the latest versions of all packages...

**Comment by rizkydiprasetya** [comment]
Aha thank you.

It is possible with Anaconda but with different way. We need to define new name for package. For example:
- conda install mlpro -> this is for full working dependencies
- conda install mlpro_base -> this is just mlpro.

Option for latest version of dependencies is not possible. Because the setuptools doesnt allow conflict dependencies.

What we can do to check the latest version of dependencie, is to upgrde it manually with --upgrade.

**Pull request merged**
