### PR TITLE
Bug: Visualization of a cluster needs to be removed when cluster itse…

### PR DESCRIPTION
**Pull request by detlefarend**
…lf is destroyed #931

### CODE REVIEW

**Comment by detlefarend** [comment]
Hi @steveyuwono, the problem of remaining plot artifacts after the removal of a cluster should be solved now. Could you please confirm and merge to main afterwards? Thx!

**Comment by steveyuwono** [comment]
> Hi @steveyuwono, the problem of remaining plot artifacts after the removal of a cluster should be solved now. Could you please confirm and merge to main afterwards? Thx!

Hi @detlefarend , thank you for the updates. The removal of clusters in the plot is now fixed. However, the red arrows (see attachment) from removed clusters still remain in the plot
image

**Comment by detlefarend** [comment]
> > Hi @steveyuwono, the problem of remaining plot artifacts after the removal of a cluster should be solved now. Could you please confirm and merge to main afterwards? Thx!
> 
> Hi @detlefarend , thank you for the updates. The removal of clusters in the plot is now fixed. However, the red arrows (see attachment) from removed clusters still remain in the plot image

Ah, of course. I'll take a look...

**Comment by detlefarend** [comment]
@steveyuwono here we go. Please check once again. Btw: Which howto did to use? I also suggest to map the cluster IDs internally to integer numbers by using an internal counter.

**Comment by steveyuwono** [comment]
> @steveyuwono here we go. Please check once again. Btw: Which howto did to use? I also suggest to map the cluster IDs internally to integer numbers by using an internal counter.

perfect, it is solved now! I am using howto_oa_ca_031 in MLPro-Int-River. Okay, I will update the cluster IDs accordingly in "oa/howtos" branch of MLPro-Int-River

**Pull request merged**
