### PR TITLE
Double pendulum environment

### PR DESCRIPTION
**Pull request by steveyuwono**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by steveyuwono** [comment]
Hi @yehiaibrahim, I have reviewed the latest version of the codes ([5765f90](https://github.com/fhswf/MLPro/pull/323/commits/5765f90f0cb84c40e5d9d828414a25db954369d6)). I made a little enhancement of the codes and solve conflicts. However, I found something is probably not right.

I have checked the updated boundaries and found it odd. Since you set up the angle of pendulums in radians, I don't think it will exceed a range of a circle, which is [-phi, phi]. Additionally, if the calculation is in degrees, it should also not exceed [-180,180]. However, the actual boundaries of the pendulums' angle seem like out of range.
https://github.com/fhswf/MLPro/blob/67be5fd8e0c700d8a8c7367921ebc7849c0fedce/src/mlpro/rl/pool/envs/doublependulum.py#L156-L167

Could you check whether the state calculations resulted in degrees or radians and solve this issue? 
https://github.com/fhswf/MLPro/blob/67be5fd8e0c700d8a8c7367921ebc7849c0fedce/src/mlpro/rl/pool/envs/doublependulum.py#L175-L231

Thank you! If you have a question, you can reach me or @detlefarend.

**Comment by steveyuwono** [comment]
Hi @yehiaibrahim @laxmikantbaheti, here are the tasks to be done, following our meeting on 01.07.2022:

- [ ] Angle 1 and angle 2 must be in degrees, we constantly use degrees as the unit for all of the variables (including set_value in __reset_ method, etc.)
- [ ] Review the calculation of angles, acceleration, and velocity in the _derivs_ method
- [ ] Use _State_ object for the return of __simulate_reaction_ method
- [ ] Run the environment and obtain boundaries empirically from the generated CSV file
- [ ] Update how to 20: Separate parameters for the demo test and internal unit test

If you have any questions, you can directly contact me or @detlefarend.

**Comment by steveyuwono** [comment]
Hi everyone @detlefarend @laxmikantbaheti @yehiaibrahim ,

I have updated the howto 20 and also reviewed the double pendulum environment. The environment works completely fine on my PC, the angle of the pendulums is always within the boundaries, such as between -180 and 180. The calculation also looks correct.

Question to @detlefarend, do we need to remove howto 21 or keep it there? If nothing else to be adjusted or added, maybe we can merge this to the main branch. What do you think?

Thank you!

**Comment by detlefarend** [comment]
Hi Laxmikant,

here's my feedback:

1. howto rl-020: 
  - shows a wonderful slow random motion:) 
  - I removed some commented code
  - I added a new piece of description 'You will learn:...' to the module docstring

2. names of classes: I would prefer the postfix S for static as the opposite of A for adaptive.

Then, I propose a slightly changed class structure:
- class **DoublePendulumRoot** (not to be used directly) 
- new class **DoublePendulumS4** (static, 4 state dim, inherited from DoublePendulumRoot)
  - ready to use
  - introduces static normalization (please name the method _normalize())
  - introduces reward strategy
- class **DoublePendulumS7** (inherited from DoublePendulumS4)
  - extends the state space to 7 dims 
  - normalization and rewarding should be the same
- future: new class **DoublePendulumA7** (inherited from DoublePendulumS4, 'adaptive, 7 dim')
  - inherits reward strategy
  - redefines methods _setup_spaces() and _normalize() and reuses MLPro-OA stuffs somehow

Here are some hints to optimize the current code:

1. class DoublePendulum: please remove or comment 
2. class DoublePendulumRoot:
    - all method parameters shall begin with p_ 
    - please add a description of the constructor parameters to the class docstring 
    - please add constants for parameter init_angles (C_ANGLES_UP, C_ANGLES_DOWN, C_ANGLES_RND)
    - please check in constructor whether parameter p_init_angles has a valid value
    - please move the constants self.C_SCIREF* to the top of the class
    - please use _ for protected attributes: self._t_step instead of self.t_step (local variables are fine!)
    - please use _ for protected methods: _derifs() instead of derifs()
    - please remove dummy implementation for rewarding
    - please implement method _compute_success()
      if metric distance between state and goal state is less than the new threshold C_THRSH_GOAL then return True

Then, regarding implementation of reward strategy: please don't use the metric of class ESpace. Please get the space of the state object like this: state.get_related_set(). It's currently the same because you initialize the state space using ESpace. But maybe someone wants to try different metrices by redefining method _setup_spaces then it still works properly.

Ok, I think that's enough for the moment. I hope my comments are understandable. Just let me know if you have questions, doubts, better ideas, ...

Thank you for your effort!

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , the env is ready for review. Following changes were made:
- Removed the note mentioning the non episodical behavour of the environment
- Added a constant for the integration step size and animation frame rate, both needed to be kept to make sure we have enough space for env with smaller time steps
- changed the current latency equal to the p_t_step (could be thought upon in Future!)
- removed t_act (could also be thought upon in future!)

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti,

here are my findings:

- [ ] API rst file
Please change order: 1) doctext from module, 2) class diagram, 3) class specification

- [ ] RTD documentation of environment
   - [ ] Note: please remove link from 'Euclidian Distance' (general knowledge)
   - [ ] Cross Reference: please check name of howto 
   - [ ] Cross Reference: please change order (howto, then api) 

- [ ] Source code
   - [ ] Classes Root, S7, method _reset, parameter p_seed
Described as not yet implemented. Please ensure seeding. Otherwise training behaviour is not reproducible.
   - [ ] Class S4, description of method _normalize
This is a concrete min/max implementation and not a custom method any more.
   - [ ] All classes: please move parameter descriptions of constructor __init__() to class description. Constructors never have a local method description.
   - [ ] All classes: please enable parameters p_mode and p_latency of root class Environment
   - [ ] All classes: please eliminate parameter p_t_step (and maybe self._t_step because it is used just twice)

- [ ] Class diagram
   - [ ] Class Root: typo in name of parent class (...Environ**em**nt instead of Environment)
   - [ ] Class Root: constant C_TYPE can be removed (because it is inherited from parent)
   - [ ] Classes S4, S7: Typo in class header (parent class Doubl**e**PendulumRoot) 
   - [ ] Classes S4, S7: Constant C_TYPE: please remove, because it is inherited from parent
   - [ ] Class S7: inherits from S4, not from root (arrow)
   - [ ] Take over all changes on class interfaces
   
- [ ] Howto RL-020
   - [ ] Scenario, C_NAME should be something like 'Double Pendulum Random'
   - [ ] Section 2: header comment describes training
   - [ ] Subsection 2.1: logging should be C_LOG_ALL to get more details
   - [ ] Subsections 2.1, 2.2: please remove dead code

Thank you!!

**Comment by laxmikantbaheti** [comment]
Wow, I missed those details. Thanks for the detailed review.

Some doubts over it:
- I did not fully understand the point of removing p_t_step and self.t_step. In that case, shall I add t_step as another constant in the env? and do we not need an option to control the step size of the environment? I have less idea about this parameter (time step).

Thanks for your efforts! So many important details highlighted.

**Comment by detlefarend** [comment]
Hi Laxmikant, 

in the current implementation p_t_step and p_latency have the same meaning. Because p_latency is a standard parameter inherited from EnvBase p_t_step is superfluous. Internal attribute self._t_step is used twice only. In constructor and in computation itself. 
Proposal: eliminate p_t_step and keep self._t_step. Initialize it like this
`self._t_step = self.get_latency().seconds + self.get_latency().microseconds / 1000000`
after(!) calling super constructor.

It's absolutely crazy: every time I take a look I find new things. But this is my last feedback for dp in this version. After this final adjustments we merge to main! 

- [ ] Classes DP*, description
    Please move the param description of constructor to the class description. 
    grafik


- [ ] Class diagram: 
   - [ ] C_NAME of classes S4, S7 (should be 'Double Pendulum S4/S7')
   - [ ] Class Root: values of constants are missing
   
- [ ] RTD, env description
   - [ ] General information, lines 3,6: please remove [] around dim number 
   - [ ] State space: static boundaries of omega and alpha 
   - [ ] Change log, version of last entry: 2.4.8 -> 2.4.11
   - [ ] Cross references: please rename the link to the howto and remove the text 'How to example file'? The link itself is self-explanatory.
   grafik
  
- [ ] Howto RL-020: seeding doesn't work. 
   Behaviour is always different. Could be policy RandomGenerator or env DP. I guess the latter one. The default implementation of method set_random_seed() in class EnvBase seeds Python's internal random generator. DP uses numpy random generator. I guess, class DBRoot needs to redefine method set_random_seed()...
Please validate: on explicite seeding the behavior must be exactly the same on every program start. Without seeding it should be real random.

**Comment by laxmikantbaheti** [comment]
Ohh sorry, I was confusing the docstrings for param descr all along, didnt notice you were mentioning 'param descr'. SORRY 

and for the random generator, I changed it from numpy generator to the inbuilt python generator, instead of creating new method. Now , the behavior is reproducible

I accept your feedback! I am adding notes what mistakes to avoid in future, thanks very much @detlefarend  😁

**Review by detlefarend — CHANGES_REQUESTED** [review]
Hi @laxmikantbaheti, I reviewed everything and refactored some things:

- I assigned the parameter lists of class constructor to class EnvBase (p_mode first, p_logging last, ...)
- In method reset() I added param p_seed to call of super method. Now the seeding behavior is fine.
- Little code optimization. I adjusted the code of S4.__init__() (number of dimensions). In consequence S7 constructor could be removed. 
- Howto: changed from S4 to S7, just to let run the code of all three classes

But I found something to be checked: DP is a symmetric problem, right? The absolute boundary values should be the same: -180, 180 for angles; -xxx, xxx for velocity etc. I propose to set these boundaries to the next smooth value: omega1 in [-800,800], omega2 in [-950, 950], alpha1 in [-6800, 6800], alpha2 in [-9700, 9700].

Could you please

- [ ] Change the boundaries in code and doc accordingly
- [ ] Adjust the class diagram
   - [ ] Classes Root, S4: new order of parameters of constructor
   - [ ] Class S7: remove constructor

Thank you!!

**Comment by laxmikantbaheti** [comment]
> But I found something to be checked: DP is a symmetric problem, right? The absolute boundary values should be the same: -180, 180 for angles; -xxx, xxx for velocity etc. I propose to set these boundaries to the next smooth value: omega1 in [-800,800], omega2 in [-950, 950], alpha1 in [-6800, 6800], alpha2 in [-9700, 9700].


Agreed the point of symmetry.

**Review by detlefarend — APPROVED** [review]
It's done! Congrats and thanks to all contributors!!

**Pull request merged**
