### PR TITLE
RTD-BF-Streams: Documentation for 3rd Party Support

### PR DESCRIPTION
**Pull request by laxmikantbaheti**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , I have added documentation for 3rd party support for stream providers. Please give me a feedback when possible. Thank you!

**Review by detlefarend — COMMENTED** [review]
Hi @laxmikantbaheti, thanks for documenting the wrappers! It is well and clear described. I would change just one thing: I would remove the last subsection "3.5.1.4.4 Accessing the Datasets" and place a **Cross Reference** part at the end of each wrapper section. Maybe, a small code box for each wrapper import as well...

**Review by detlefarend — APPROVED** [review]
Hi @laxmikantbaheti, now it's good. I just corrected some last things: scikit-learn instead Scikitlearn and 1/2 typos. Furthermore, I added a link to the source in the rtd description of howto 051 so that it is also accessible. I'll merge...

**Comment by laxmikantbaheti** [comment]
> Hi @laxmikantbaheti, now it's good. I just corrected some last things: scikit-learn instead Scikitlearn and 1/2 typos. Furthermore, I added a link to the source in the rtd description of howto 051 so that it is also accessible. I'll merge...

Thanks!

**Pull request merged**
