### PR TITLE
Model improvements15

### PR DESCRIPTION
**Pull request by detlefarend**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by detlefarend** [comment]
Hi @steveyuwono, I just reviewed the HPT extensions. Here are some annotations:

Class HyperParamDispatcher:
- Method add_hp_tuple: what is the intention of line 112 (try-path)? Existence check of dict _hp_dict? Maybe it would be a litte bit cleaner to redefine and extend the constructor to add the dict.

- Methods get_values(), set_values: just a little code optimization by using enumerate
  Instead of this 
```python
    def get_values(self):
        for idx in range(len(self._set.get_dim_ids())):
            dim_id = self._set.get_dim_ids()[idx]
            self._values[idx] = self.get_value(dim_id)
        return self._values
```
  you could do this

```python
    def get_values(self):
        for idx, dim_id in enumerate(self._set.get_dim_ids()):
            self._values[idx] = self.get_value(dim_id)
        return self._values
```

Class WrHPTHyperopt:
- Super class Log not necessary because it's part of HyperParamTuner
- Method _ofct_hyperopt(): same code optimization by using enumerate in l. 188-190 and 198-201
- Method SetupSpaces(): please lower case. Code optimization by using enumerate in l. 230-

Class MultiAgent:
- The hyperparams must be updated/extended in method add_agent instead of in _init_hyperparam() 

Howto 07 is not yet executable

**Comment by steveyuwono** [comment]
Hi @detlefarend, I deleted the previous message because the codes do not pass the pytest. However now, they do. I have updated the codes and they are ready to be reviewed. I have tested Howto 07 and it can be executed. You can review it again and let me know if there is anything to be improved. Otherwise, I will merge it with the main branch. Thank you!

**Comment by detlefarend** [comment]
Hi @steveyuwono, I reformatted a little and reworked HyperParamDispatcher.set_values(). I think it's fine now. I'll merge to main.

**Comment by steveyuwono** [comment]
Okay great, thank you!

**Pull request merged**
