### PR TITLE
BF: New base class FctSTrans

### PR DESCRIPTION
**Pull request by detlefarend**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by rizkydiprasetya** [comment]
Looks good to me. A question:
- What is the sense of success in System Class? For broken I can imagine if the system can be broken in a certain pre-defined conditions (e.g fail on sensor, fail on actuator).

**Comment by detlefarend** [comment]
> Looks good to me. A question:
> 
>     * What is the sense of success in System Class? For broken I can imagine if the system can be broken in a certain pre-defined conditions (e.g fail on sensor, fail on actuator). And if the current state is not broken, means that the system is running properly.

Finally, system is an rl env without reward functionalities and adaptation. Success and broken are optional and have the same semantics as on rl level. Success means that the system reached a state that is close enough to a specific goal. Broken means the system has reached a point of no return and is lost. Cartpole: broken = fallen down, success = straighten up. The surrounding process has to deal with these informations. 

However, your question made me think of some details again. I sharpened the default implementations and documentations of the system's custom methods for success and broken...

**Comment by rizkydiprasetya** [comment]
> Success means that the system reached a state that is close enough to a specific goal. Broken means the system has reached a point of no return and is lost. Cartpole: broken = fallen down, success = straighten up. The surrounding process has to deal with these informations.

This sounds like an RL environment, not a system.

**Comment by detlefarend** [comment]
It's an optional functionality to qualify states. In this systematics a system becomes an rl environment by adding
- reward functionality
- episode management
I mean it's plausible. Again the cartpole: if you remove the rewarding then it's nothing else than a state based system with a defined goal and also defined "lost" state areas. Could also be a part of a "classic" control loop.

**Comment by detlefarend** [comment]
@rizkydiprasetya @laxmikantbaheti any further doubts or proposals to do something better?

**Review by laxmikantbaheti — APPROVED** [review]
Hello @detlefarend , this looks good!
A generic base class.

**Review by rizkydiprasetya — APPROVED** [review]

**Pull request merged**
