### PR TITLE
WR: MuJoCo Wrapper

### PR DESCRIPTION
**Pull request by rizkydiprasetya**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Review by detlefarend — COMMENTED** [review]
Hi @rizkydiprasetya, I just took a look. In my opinion a clean and proper integration. Here's some feedback on the current state of implementation:

- XML file
   I found out that MuJoCo basically supports two file formats: [MJCF and URDF](https://mujoco.readthedocs.io/en/stable/modeling.html). Is the current implementation limited to MJCF or is it easy to extend the wrapper to URDF?

- Merge SystemBase and System?
  I don't know whether this separation helps anyone. The difference is just the additional controller logic that is optional. We could do the same thing you did for MuJoCo: we call the custom methods if no controller was added before...

- bf.systems as sub-package
  I think we should make it a sub-package (=folder with __init__.py file). We can add a sub-package ./pool for various MuJoCo sample systems like inverted pendulum, double pendulum, etc.

- Howto 
  The howto is running properly. I just propose reducing the number of cycles to a necessary minimum of 2-5 in unit test mode. Maybe you could log the states and actions with boundaries, short names, basic data types, ... in advance to demonstrate that we can extract these informations from the MuJoCo system.

- Idea: support for the [MuJoCo Menagerie](https://mujoco.readthedocs.io/en/stable/models.html) 
   Maybe further howtos for it...

**Comment by rizkydiprasetya** [comment]
1. I know it supports URDF, but its limited. So I will suggest to stick with default format.
2. Agreed, I can only see this controller management as the difference.
3. You meant, instead of wrapper, we put it on bf.systems? I dont understand.
4. Ok.
5. I will have a look.

**Comment by detlefarend** [comment]
> 1. I know it supports URDF, but it's limited. So I will suggest to stick with default format.
>
Ok, but please let's keep this in mind due to robotics(...) I estimate that URDF is the much more spread exchange format and maybe a kind of industry standard for robotics. MJCF is restricted to MuJoCo and as such probably not very spread in the industry - even if it's the better format.
 
>     2. Agreed, I can only see this controller management as the difference.
> 
>     3. You meant, instead of wrapper, we put it on bf.systems? I dont understand.
> 
No, the wrapper itself is fine and the integration is also. I propose to replace the current module systems.py with a folder ./systems with a module basics.py and a further sub-folder ./pool inside. I can take over this part, maybe next Friday after a review with the colleagues. See #597 
>     4. Ok.
> 
>     5. I will have a look.

**Comment by rizkydiprasetya** [comment]
1. We can make it proper. But we need to write URDF to MJCF converter and the other way around, to remove the limitation. I can do this but not in version 1.0.0.

**Pull request closed without merging**
