### PR TITLE
Model improvements #9

### PR DESCRIPTION
**Pull request by detlefarend**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by detlefarend** [comment]
Hi colleagues, I extended the result file evaluations.csv of class RLTraining by a new column "Adaptations". So we can add a curve for it that shows the adaptation activities of the agent. Furthermore I fixed a bug on counting stagnations.

**Comment by detlefarend** [comment]
Added moving average score computation. See #265 for more details. Please review.

**Review by steveyuwono — APPROVED** [review]
ok

**Review by rizkydiprasetya — APPROVED** [review]
OK

**Pull request merged**
