### PR TITLE
BF: Persistence

### PR DESCRIPTION
**Pull request by detlefarend**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by rizkydiprasetya** [comment]
Ok I will check.

**Comment by rizkydiprasetya** [comment]
Fyi, It doesn't work also on my local. So I will check again more.

**Comment by detlefarend** [comment]
@steveyuwono @rizkydiprasetya @laxmikantbaheti, the technical properties of the new class **Persistent** have been validated by Steve and myself. It would be nice if you could read/review the related rtd section and give me feedback. Thanks in advance!

**Comment by laxmikantbaheti** [comment]
Hi everyone, I am currently having problems with RTD Build, specifically importing the jquery extension, although I have installed all the requirements.

**Comment by detlefarend** [comment]
> > @steveyuwono @rizkydiprasetya @laxmikantbaheti, the technical properties of the new class **Persistent** have been
> 
> Hi everyone, I am currently having problems with RTD Build, specifically importing the jquery extension, although I have installed all the requirements. What can be possible reasons?

Hey ho, did you try to remove local folder mlpro/doc/rtd/_build?

**Comment by laxmikantbaheti** [comment]
> Hey ho, did you try to remove local folder mlpro/doc/rtd/_build?

That worked. Thanks 👍

**Comment by laxmikantbaheti** [comment]
> @steveyuwono @rizkydiprasetya @laxmikantbaheti, the technical properties of the new class **Persistent** have been validated by Steve and myself. It would be nice if you could read/review the related rtd section and give me feedback. Thanks in advance!

Hi @detlefarend , the documentation looks good. It's straightforward to understand all the methods. But, in sections "Saving Objects" and "Loading Objects" , the content becomes discontinuous because of the block (stating default file names in for saving, and attribute "C_PERSISTENCE_VERSION"). Like half of the sentence is above the block and the rest starts below.

**Comment by steveyuwono** [comment]
> @steveyuwono @rizkydiprasetya @laxmikantbaheti, the technical properties of the new class **Persistent** have been validated by Steve and myself. It would be nice if you could read/review the related rtd section and give me feedback. Thanks in advance!

Hi Detlef, after several updates, the documentation looks clear and understandable.

**Review by laxmikantbaheti — APPROVED** [review]

**Review by steveyuwono — APPROVED** [review]

**Review by rizkydiprasetya — APPROVED** [review]

**Pull request merged**
