### PR TITLE
BF: Add howto examples MuJoCo with image from camera

### PR DESCRIPTION
**Pull request by rizkydiprasetya**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by rizkydiprasetya** [comment]
@detlefarend @steveyuwono maybe useful for your OA stuff with CV. Run Howto bf_systems_004. This is also some preparation for my other stuff.

**Review by detlefarend — COMMENTED** [review]
Hi Rizky, this is very interesting, inspiring, and relevant. It is a step ahead to open the black box MuJoCo and integrate parts. Could you please integrate it in rtd? If it is unsuitable for background processing/unit testing, you could refer to the src file directly in the howto.rst (like we did for howto_bf_streams_051_accessing_data_from_openml.py).

The howto raises the question of pooling and integrating CV components in MLPro. Currently, I think a CV component is more an adaptive function than a state-based system because it has no inner state in the simplest case. It maps an image to specific positional output information. That brings me to the point that we need a special StreamTask implementation that applies a (pre-trained) (adaptive) function to incoming stream data instances... A further StreamTask could integrate a state-based system to map an input instance (=action) to an output instance (=state)... However, this is a different story...

**Comment by detlefarend** [comment]
> > Hi Rizky, this is very interesting, inspiring, and relevant. It is a step ahead to open the black box MuJoCo and integrate parts. Could you please integrate it in rtd? If it is unsuitable for background processing/unit testing, you could refer to the src file directly in the howto.rst (like we did for howto_bf_streams_051_accessing_data_from_openml.py).
> 
> Done.

Please also add a new cross reference entry to rtd-bf-systems-mujoco. It would also be nice to take a gif snapshot and add it to the howto description. The doc-string of the howto should also be taken over to the howto.rst. Thx!

**Comment by rizkydiprasetya** [comment]
> 

#725

**Pull request merged**
