### PR TITLE
ReadTheDocs - Introduction

### PR DESCRIPTION
**Pull request by detlefarend**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by detlefarend** [comment]
Hi @rizkydiprasetya @steveyuwono @laxmikantbaheti, I just finalized our entry page and the main navigation. In detail I changed the following:
- Entry page: toc removed
- Entry page: all tiles lead to related sub-tocs
- Section 1: Changed some terms and simplified section structure
- Subsection 1.2: image for architecture

Textual content still in progress...

Would be cool if you could take a look - maybe in different browsers. I just checked with Firefox.

It's the first thing a visitor sees and as such it heavily influences the first impression of MLPro. So please give me an open feedback. Is there anything we can do better?

**Comment by steveyuwono** [comment]
> Hi @rizkydiprasetya @steveyuwono @laxmikantbaheti, I just finalized our entry page and the main navigation. In detail I changed the following:
> 
> * Entry page: toc removed
> * Entry page: all tiles lead to related sub-tocs
> * Section 1: Changed some terms and simplified section structure
> * Subsection 1.2: image for architecture
> 
> Textual content still in progress...
> 
> Would be cool if you could take a look - maybe in different browsers. I just checked with Firefox.
> 
> It's the first thing a visitor sees and as such it heavily influences the first impression of MLPro. So please give me an open feedback. Is there anything we can do better?

Hi, I checked it using google chrome and I think this generally looks good, especially since the home page becomes simpler and more attractive. However, we still need to add more content, specifically in point 1.2 and maybe also 1.1. Then, I have some comments, as follows:

1. The titles in the toc trees are missing. Here is an example:
image

2. If possible, it might make sense to be able to click the main sections (see photo below) and link them with the related page, e.g. "1. WELCOME TO MLPRO" is linked to index_01_welcome.rst
image

3. I have no idea whether 'onboarding' suits the subsection title because it sounds odd to me. But, it is maybe just because I have very rarely heard about it. Suggestions: getting started, basic guides, basic usage

**Comment by detlefarend** [comment]
Hi @steveyuwono, thanks for your feedback. I was able to solve the "no title"-problem. Regarding the blue head lines in the left menu: here I didn't find a way. These are just captions and unfortunately they can't be linked to something. For instance, it's the same in [stable-baselines3](https://stable-baselines3.readthedocs.io/en/master/). Then, I changed the name of subsection 1.2 to "Getting Started". I add further textual content in the next days...

**Comment by rizkydiprasetya** [comment]
Checked on safari, looks good. On 1.2 Getting Started, we should also mention the installation option.

**Comment by steveyuwono** [comment]
> Hi @steveyuwono, thanks for your feedback. I was able to solve the "no title"-problem. Regarding the blue head lines in the left menu: here I didn't find a way. These are just captions and unfortunately they can't be linked to something. For instance, it's the same in [stable-baselines3](https://stable-baselines3.readthedocs.io/en/master/). Then, I changed the name of subsection 1.2 to "Getting Started". I add further textual content in the next days...

Great, thank you. Everything looks fine so far

**Comment by detlefarend** [comment]
> Checked on safari, looks good. On 1.2 Getting Started, we should also mention the installation option.

Definitely!

**Pull request closed without merging**
