### PR TITLE
WR: Stable Baseline 3

### PR DESCRIPTION
**Pull request by rizkydiprasetya**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by rizkydiprasetya** [comment]
Just a little changes...

**Review by steveyuwono — APPROVED** [review]
Looks fine to me..

**Comment by detlefarend** [comment]
@rizkydiprasetya Please check/update the meta data of the related issues: milestone, label, project, ... and delete the branch after that (if you don't need it any more).

**Comment by detlefarend** [comment]
@rizkydiprasetya The issues are still incomplete. Please update and let me know if you have done. I don't want to poll for it any more. You know our project rules...

**Comment by rizkydiprasetya** [comment]
@detlefarend I dont know what you are talking about. Look below, it is closed.....

image

**Comment by detlefarend** [comment]
@rizkydiprasetya read my posts! I am talking about the related issues and their metadata: milestones, labels, project.

**Comment by rizkydiprasetya** [comment]
Done

**Pull request merged**
