### PR TITLE
RL: Add multi-processing on MPC

### PR DESCRIPTION
**Pull request by steveyuwono**
## Description

- [ ] #418
- [ ] #416
- [ ] Update related howtos

## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by steveyuwono** [comment]
- Multiprocessing on MultiAgent for action computation (AC) and policy adaptation (PA)
  - Note: For loop in action computation can not be avoided, because we need to create the Action object and fill it with the element of each agent
  - Multi-cart pole with 10 agents and 10000 cycles:
    - C_RANGE_NONE = 03:33.930507
    - C_RANGE_THREAD = 03:35.250195 (CA&PA), 03:34.947933 (PA)
    - C_RANGE_PROCESS = Error

- Multiprocessing on MPC
  - MPC as action planner on Grid World (planning width = 50, cycles = 500):
    - C_RANGE_NONE = 00:26.367613
    - C_RANGE_THREAD = 00:26.156961
    - C_RANGE_PROCESS = Error
  - MPC as action planner on Grid World (planning width = 500, cycles = 10000):
    - C_RANGE_NONE = 03:47.080091 (CPU utilization ±70%)
    - C_RANGE_THREAD = 01:10.993367 (CPU utilization ±98%)
    - C_RANGE_PROCESS = Error
  
- C_RANGE_PROCESS error message:
image
image

**Comment by detlefarend** [comment]
Hi Steve, I'll take a look later on and give feedback...

**Comment by steveyuwono** [comment]
> Hi Steve, I'll take a look later on and give feedback...
> 
> In the meantime you could try to run your multiprocessing experiment under Linux. The error message is normally related to Windows.

Hi Detlef, you can check this after your holiday or we can discuss this in our meeting next week. This is not so urgent and some changes might also be made in the next couple of days. I was writing it here just as a note and a reminder. Okay, I will try to run them under Linux.

**Comment by steveyuwono** [comment]
I tested them on Linux using Virtual Machine, so maybe it is not the best in terms of performance. However, multiprocessing using C_RANGE_PROCESS works completely fine. Significant improvement has shown up for MBRL training using MPC, but not for MultiAgent scenario. But anyway, I will review this further. Here are the results:

- Multiprocessing on MultiAgent
  - Multi-cart pole with 10 agents and 10000 cycles:
    - C_RANGE_NONE = 05:24.026137
    - C_RANGE_THREAD = 06:10.800048
    - C_RANGE_PROCESS = 06:11.998692

- Multiprocessing on MPC
  - MPC as action planner on Grid World (planning width = 500, cycles = 10000):
    - C_RANGE_NONE = 06:56.787673
    - C_RANGE_THREAD = 03:55.034379
    - C_RANGE_PROCESS = 02:15.945964

**Pull request merged**
