### PR TITLE
BF-Math: Z-transform update - parameter update based on single new data instance

### LINKED ISSUE #444: BF-MATH: Possibility to udpate parameters of z-transformer with single data element based on running mean and standard deviation
The z-transformer should be able to update on instance/data element

**Task list**
- [x] Update the update_parameters method for p_instance
- [x] update the Howto to demonstrate the feature
- [x] update the class diagram

### PR DESCRIPTION
**Pull request by laxmikantbaheti**
Z-transofrm parameters can now be updated with a single new data element

## Background

#444 

closes #444 
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Review by detlefarend — CHANGES_REQUESTED** [review]
Hi Laxmikant,

just some annotations:
- I beautified the class diagram a bit (solid class boxes with shades)
- All normalizer classes, method update_parameters
  They return contant True. If there is no case of returning False then the return value can be removed.
- Class NormalizerMinMax, method update_parameters
  I think the code can be tuned a bit. Currently you append the new parameters to lists and create new np.array based on them. I propose to create and assign the arrays once and update the values within directly. Should be faster and prevents the memory from being fragmented.
- Perhaps t's a similar thing for class NormalizerZTrans

**Comment by detlefarend** [comment]
@laxmikantbaheti Are you still working on this or do you wait for a further review?

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , I just need to do some further refactoring.

**Comment by detlefarend** [comment]
@laxmikantbaheti Green! I'll wait for your trigger...

**Comment by laxmikantbaheti** [comment]
> In method update_parameters() of ZTrans normalizer line 238 is hot: p_data is potentially a parameter by reference. That means you change the data of the calling layer. 

ohh yes! I do get confused sometimes with this reference based variables.

**Review by detlefarend — APPROVED** [review]
Everything is fine.

**Pull request merged**
