### PR TITLE
RTD: Final Documentation v1.0.0

### PR DESCRIPTION
**Pull request by detlefarend**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by detlefarend** [comment]
Hi guys, as mentioned I replaced branches rtd_intro, rtd_bf by the new and final branch rtd_v1.0.0. Next step is to restructure everything as described in #584. After that I let you know so that we can go on filling content to the docu...

**Comment by detlefarend** [comment]
Hi @steveyuwono, just a small hint regarding import of gt, rl, ... It is not necessary any more to refer to submodules.

**Comment by steveyuwono** [comment]
> Hi @steveyuwono, just a small hint regarding import of gt, rl, ... It is not necessary any more to refer to submodules.
> 
> 

Thank you for reminding me.

**Comment by rizkydiprasetya** [comment]
@detlefarend @steveyuwono @laxmikantbaheti sorry guys for a lot of changes. It works now. I was trying to combine CI jobs in one file, and triggering one job with another job. Anyway, now the dependencies list are generated in a file called "deps.txt".

**Comment by detlefarend** [comment]
Hi @steveyuwono, could you please add class ScientificObject to the class diagram? Thx!

**Comment by detlefarend** [comment]
Hi @rizkydiprasetya, could you please beautify module bf.data.py and add a class diagram? Merci!

**Review by laxmikantbaheti — APPROVED** [review]

**Pull request merged**
