### PR TITLE
RL Solution for Double Pendulum Env.

### PR DESCRIPTION
**Pull request by steveyuwono**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by steveyuwono** [comment]
For plotting rewards and evaluation scores, you can apply the following codes:
[plot.zip](https://github.com/fhswf/MLPro/files/9536351/plot.zip)

**Comment by laxmikantbaheti** [comment]
Screenshot 2022-09-29 235928

current boundaries suggested by the double pendulum environment

**Comment by detlefarend** [comment]
Hi colleagues, I just played a bit with new howto rl-022. At first, this howto is very helpful. I propose to make it an official second howto for the dp. I also propose to turn off logging here due to the user inputs. Regarding the behavior I think that the torque is incorporated correctly. I am not that sure about the following: I started with 50Nm for 1 cycle. After that I added many cycles without any torque (>1000). My expectation was that the dp does some chaotic cycles and then swings out after a while and stands still in vertical end position due to gravity. But it is a never-ending chaotic motion. I know that we don't simulate air resistance or friction but we have a permanent vertical acceleration due to gravity... I guess it's correct because of conservation of momentum.

**Comment by detlefarend** [comment]
Hi @steveyuwono @laxmikantbaheti I'll do the refactoring of the dp env in this branch. Can we merge to main after this?

**Comment by steveyuwono** [comment]
> Hi @steveyuwono @laxmikantbaheti I'll do the refactoring of the dp env in this branch. Can we merge to main after this?

For me, it's fine

**Comment by laxmikantbaheti** [comment]
Yes, me too.

**Review by detlefarend — APPROVED** [review]
DP is not yet solved. The rest is to be merged to main due to prio corrections.

**Pull request merged**
