### PR TITLE
OA: Initial implementation of core classes

### PR DESCRIPTION
**Pull request by detlefarend**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by detlefarend** [comment]
@laxmikantbaheti @steveyuwono @syam47: Hi Guys, I propose the following design extension on class OATask. It introduces a new optional custom method _adapt_reverse() that adapts the inner policy by removing instances. Method _adapt() is now limited to policy adaptations on new instances:

grafik


@laxmikantbaheti: I have already refactored classes BoundaryDetector and NormalizerZTransform. I have two annotations:

a) BoundaryDetector
Doesn't currently implement a reverse adaptation.

b) NormalizerZTransform
Could you please add a window task to howto_oa_pp_002_normalization_of_streamed_data_ztransform to validate the reverse adaptation?

**Comment by laxmikantbaheti** [comment]
> @laxmikantbaheti @steveyuwono @syam47: Hi Guys, I propose the following design extension on class OATask. It introduces a new optional custom method _adapt_reverse() that adapts the inner policy by removing instances. Method _adapt() is now limited to policy adaptations on new instances:
> 
> grafik
> 
> @laxmikantbaheti: I have already refactored classes BoundaryDetector and NormalizerZTransform. I have two annotations:
> 
> a) BoundaryDetector Doesn't currently implement a reverse adaptation.
> 
> b) NormalizerZTransform Could you please add a window task to howto_oa_pp_002_normalization_of_streamed_data_ztransform to validate the reverse adaptation?

Hi @detlefarend , thanks for refactoring. I will validate the same as mentioned and let you know...

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , the reverse_adapt works as intended in z transform. Thank you!

**Comment by detlefarend** [comment]
> Hi @detlefarend , the reverse_adapt works as intended in z transform. Thank you!

@laxmikantbaheti can it be that you forgot merging your changes? The howto is untouched.

**Comment by detlefarend** [comment]
@laxmikantbaheti @syam47 @steveyuwono I have restructured/renamed the class diagrams. They are organized in two sub-folders ./streams and ./systems now.

**Comment by laxmikantbaheti** [comment]
> > Hi @detlefarend , the reverse_adapt works as intended in z transform. Thank you!
> 
> @laxmikantbaheti can it be that you forgot merging your changes? The howto is untouched.

Oops, error on my side. Fixed it.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, 

I found a problem with the MinMax normalizer/boundary detector in combination with MLPro sample stream StreamMLProStaticClouds2D. Could you please take a look at **howto_oa_pp_001_normalization_of_streamed_data_minmax.py**? I changed the stream in line 49. If you run it, the following exception occurs after just a couple of instances...



The problem occurs, because I removed the boundaries from the sample stream features:



The exception is raised in method NormalizerMinMax._update_plot_2d(), l. 170:

**Comment by detlefarend** [comment]
Hi  @laxmikantbaheti, I found the critical code sequence in methods NormalizerMinMax._update_plot_2d/3d/nd. I'll fix it and come back with an update...

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , thanks for informing. Have you already fixed it?
I can work on it now, if it's okay.

**Comment by detlefarend** [comment]
> Hi @laxmikantbaheti, I found the critical code sequence in methods NormalizerMinMax._update_plot_2d/3d/nd. I'll fix it and come back with an update...

The problem was, that the internal np array was created only once. But this is necessary, whenever the size of the underlying data lists changes:



Same story in _update_plot_3d/nd...

Independently, 
- creating a new array
- flooding it pythonic in (cascaded) for-loops 
- renormalize all feature data, even if only one of then needs to be renormalized
- re-flooding the plot lists from the array in further for-loops
is very expensive and fragments the memory. 

I propose a feature-wise re-/de/-normalizing strategy directly on the origin data. I'll add an issue for it.

I propose to

**Comment by laxmikantbaheti** [comment]
> > Hi @laxmikantbaheti, I found the critical code sequence in methods NormalizerMinMax._update_plot_2d/3d/nd. I'll fix it and come back with an update...
> 
> The problem was, that the internal np array was created only once. But this is necessary, whenever the size of the underlying data lists changes:
> 
> 
> 
> Same story in _update_plot_3d/nd...
> 
> Independently, 
> - creating a new array
> - flooding it pythonic in (cascaded) for-loops 
> - renormalize all feature data, even if only one of them needs to be renormalized
> - re-flooding the plot lists from the array in further for-loops
> 
> is very expensive and fragments the memory. 
> 
> I propose a feature-wise re-/de/-normalizing strategy directly on the origin data. I'll add an issue for it.
> 


Sure. Thanks for detailed review.
Are you working on it? Or shall I take it over?

**Comment by detlefarend** [comment]
> > > Hi @laxmikantbaheti, I found the critical code sequence in methods NormalizerMinMax._update_plot_2d/3d/nd. I'll fix it and come back with an update...
> > 
> > 
> > The problem was, that the internal np array was created only once. But this is necessary, whenever the size of the underlying data lists changes:
> > 
> > Same story in _update_plot_3d/nd...
> > Independently,
> > 
> > * creating a new array
> > * flooding it pythonic in (cascaded) for-loops
> > * renormalize all feature data, even if only one of them needs to be renormalized
> > * re-flooding the plot lists from the array in further for-loops
> > 
> > is very expensive and fragments the memory.
> > I propose a feature-wise re-/de/-normalizing strategy directly on the origin data. I'll add an issue for it.
> 
> Sure. Thanks for detailed review. Are you currently working on it? Or shall I take it over?

The concrete problem is fixed. The optimization is not urgent. However, if you have an idea for an improvement, then feel free.

**Pull request merged**
