### PR TITLE
RTD Edit

### PR DESCRIPTION
**Pull request by rizkydiprasetya**
## Description

Edit RTD

## Background

New environment added to the pool

## Types of changes

- [ ] Bug fix
- [ ] New Example, please read the detailed guideline [here](https://www.google.com)
- [ ] New Feature
- [x] Documentation

## New Feature

- [ ] Model (Improvement on the Core Model)
- [ ] Environment (New Environment), please read the detailed guideline [here](https://www.google.com)
- [ ] Policy (New Policy), please read the detailed guideline [here](https://www.google.com)
- [ ] .....

## Checklist:

- [x] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide.
- [ ] Update the history on the source code (**required**).
- [ ] This change requires a change to the documentation.
- [ ] Update the tests accordingly.
- [x] Update the documentation accordingly.

### CODE REVIEW

**Comment by detlefarend** [comment]
Hi Rizky, 

it would be cool to have a short initial description of the purpose of the env at the beginning. At the end we have this passage **version structure**. I think I would remove the hint to the related mlpro version. We see the docu of v0.8.1 and describe let's say version 1.4.0 of the env. Referring explicitely to mlpro version is hard to maintain. 

Btw: what is the big difference between the UR5JointControl env and the new MultiGeo env? Is it kind of joints versus destination point? Is MultiGeo also related to UR5 or a different configuration? To me it looks similar.

**Comment by detlefarend** [comment]
I removed redundant information from README.md to avoid multi-maintenance of the same things.

**Comment by rizkydiprasetya** [comment]
Ok, I will put something on the description.

MultiGeo and UR5 have the same framework, using ROS. But, UR5 env is based on UR5 robot product. MultiGeo, like the name itself, multi geometry, the geometry of the robot is based on user configuration, let say, number of arm, mass of the arm, joint number, and so on.

**Comment by detlefarend** [comment]
> Ok, I will put something on the description.
> 
> MultiGeo and UR5 have the same framework, using ROS. But, UR5 env is based on UR5 robot product. MultiGeo, like the name itself, multi geometry, the geometry of the robot is based on user configuration, let say, number of arm, mass of the arm, joint number, and so on.

Ah, I see. Cool stuff!

**Comment by detlefarend** [comment]
Before we tag 0.8.1 I would like to change some further things. I saved some of the diagrams on 200% to improve the quality. The effect is a double sized view. That was not really a good idea...

**Review by detlefarend — APPROVED** [review]

**Pull request merged**
