### PR TITLE
Supervised Learning and Pytorch Adaptive Function

### PR DESCRIPTION
**Pull request by rizkydiprasetya**
## Description

Policy Net Wrapper from a customised policy net mlpro to stable baselines

## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by detlefarend** [comment]
Hi @rizkydiprasetya, please assign the related issue(s) and let me know the missing SL functionalities needed for your nn implementation. Thx!

**Comment by detlefarend** [comment]
Hi @rizkydiprasetya, I am not sure about the current state of this activity. Could you please assign the related issues and give me an info about the missing SL functionalities or the needs for a (partial) redesign/extension of framework functionalities? Should we schedule an appointment - let's say next Friday in the lab?

**Comment by rizkydiprasetya** [comment]
- [ ] SL Training
- [ ] SL Scenario
- [ ] SL Dataset

The question is the following, I have dataset and I want to train my neural network, how can I do that with MLPro?

**Comment by detlefarend** [comment]
You are right! We need this for adaptive functions that buffer the data and process a single training if the buffers ran full. Shall we discuss this this Friday in the lab? Maybe after lunch?

**Comment by rizkydiprasetya** [comment]
Sure

**Pull request closed without merging**
