### PR TITLE
Quality Assurance v1.0.0-3

### PR DESCRIPTION
**Pull request by laxmikantbaheti**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by detlefarend** [comment]
Hi @steveyuwono, there are currently two classes TransferFunction - in bf.physics and bf.systems. Is this correct or can one them be removed?

**Comment by detlefarend** [comment]
Hi @steveyuwono @laxmikantbaheti @rizkydiprasetya, I cleaned up/renamed some howtos related to rl training. In particular, two new howtos rl_att_001/002 demonstrate stagnation detection on the gym/mujoco cart pole env. RTD is already updated accordingly.

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , currently I am not able to save the scenario or the environment after a training run:
 - Currently there are two types of custom _save methods: one at systems level and other on specific wrappers
 - I think, the one at the systems level expects the system to only be a mujoco one.
 Thus, in case of Howto-RL-Env 004 for DP, it fails at the end before saving.
Also, is it true correct that the states, action and reward CSVs are no longer saved?

**Comment by detlefarend** [comment]
> Hi @detlefarend , currently I am not able to save the scenario or the environment after a training run:
> 
>     * Currently there are two types of custom _save methods: one at systems level and other on specific wrappers
> 
>     * I think, the one at the systems level expects the system to only be a mujoco one.
> 
> 
> Thus, in case of Howto-RL-Env 004 for DP, it fails at the end before saving. Also, is it true correct that the states, action and reward CSVs are no longer saved?

I'll take a look...

**Comment by detlefarend** [comment]
> > Hi @detlefarend , currently I am not able to save the scenario or the environment after a training run:
> > ```
> > * Currently there are two types of custom _save methods: one at systems level and other on specific wrappers
> > 
> > * I think, the one at the systems level expects the system to only be a mujoco one.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thus, in case of Howto-RL-Env 004 for DP, it fails at the end before saving. Also, is it true correct that the states, action and reward CSVs are no longer saved?
> 
> I'll take a look...

@laxmikantbaheti I currently get this error:

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , this is a new one 😅,
Yesterday I was having an error saying no attribute named _mujoco_file()

**Comment by detlefarend** [comment]
@laxmikantbaheti I tried to fix the error, but I can't test it myself. Could you retry the dp howto and let me know? Thx!

**Comment by laxmikantbaheti** [comment]
> @laxmikantbaheti I tried to fix the error, but I can't test it myself. Could you retry the dp howto and let me know? Thx!

Hi @detlefarend , it works now, thanks!

**Comment by rizkydiprasetya** [comment]
@detlefarend why the numbering so far away? I just followed the previous number. But if you want to start from 2x, then I will change it.

**Comment by detlefarend** [comment]
> @detlefarend why the numbering so far away? I just followed the previous number. But if you want to start from 2x, then I will change it.

We currently invest much time to clean up all the howtos of 2 years and to bring them into a logical order. Please name the new howtos as mentioned and ask for next names/numbers before you add further howtos. Please also check for redundancy as also mentioned. It makes no sense to present the same things twice or more. 

Please also recap our last slack chat.

**Comment by detlefarend** [comment]
@rizkydiprasetya, here's my feedback regarding mujoco integration:

a) RTD
- please re-check the grammar -> Grammarly for singular/plural etc.
- please check the creation process: it is not necessary to set up a custom system
- cross references: howto's shall be referred using the full title (e.g. "Howto BF-SYSTEMS-002: Double Pendulum Systems wrapped with MuJoCo" instead of "Howto BF System 002")
- eye catcher gifs on top are nice

b) Howtos
- howto-bf-systems-002: custom system can be removed

c) MuJoCo integration
- Name of the system (for logging): I propose an optional parameter p_name for it. If not supplied, we could use the file name w/o path
- Latency: should be taken over from XML file if possible. If not, parameter p_latency should be obligatory.

d) MuJoCo tools
- What viewer are you using for mujoco files? Is it unity or something else? If not unity then please refer to it.

e) Cart pole / DP
Of course, it looks fency. Nevertheless, I suggest some minor changes to help the user to see and understand the behavior of the system better:
- MLPro logo smaller and in the top/bottom right  corner (but please keep the white background)
- Brighten up the scene a bit (maybe a second light source)
- Avoid white or gray object color to have a better contrast to the white background (cart pole)
- x/y/z axes: I would try to make them look a bit more scientific. Smaller diameter, characters x,y,z at the end of the arrows (if easily possible). One color for all axes. Something like that...

**Comment by rizkydiprasetya** [comment]
@detlefarend just a note. Color of the axes are standard in 3D world. X is always red, Y is always green, Z is always blue. So I would keep the color and put the character as you suggested.

**Comment by detlefarend** [comment]
> @detlefarend just a note. Color of the axes are standard in 3D world. X is always red, Y is always green, Z is always blue. So I would keep the color and put the character as you suggested.

Ok, that makes sense.

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , I've added documentation for the bf: systems and bf: systems: hardware access. Could you please take a look when possible? 
Maybe there's room for more in hardware access. Let me know your opinion.

**Comment by detlefarend** [comment]
> Hi @detlefarend , I've added documentation for the bf: systems and bf: systems: hardware access. Could you please take a look when possible? Maybe there's room for more in hardware access. Let me know your opinion.

Hey ho @laxmikantbaheti, here's my feedback:
- I would consequently use the terminology state-based (with minus) and state (instead of status)
grafik

- Learn more and Cross Reference (instead Reference**s**)
grafik

- Cross Reference: "API Reference BF-Systems" instead of "BF-SYSTEMS - State-based Systems"

- Sample Pool: should be mentioned - also in appendix 2.

Thx!

**Comment by laxmikantbaheti** [comment]
> * Sample Pool: should be mentioned - also in appendix 2.

Hi @detlefarend , I think, currently we don't have documentation for Systems pool objects, also in appendix 2. Did you mean the same?

**Pull request merged**
