### PR TITLE
RL-Train: turned off training data logging on eval

### PR DESCRIPTION
**Pull request by detlefarend**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by steveyuwono** [comment]
I think that it is still storing all the data during the evaluation phase. I checked the frame_id in the RLDataSotring object and plot the ds_rewards as well. But it shows 30 episodes (20 training ep and 10 eval ep).

image
image
image

**Comment by rizkydiprasetya** [comment]
Yes, it is still storing.

**Comment by detlefarend** [comment]
Howto 17 is running properly: 40 training episodes, 5 evaluations. The training data files for sar contain data for 40 training episodes. Do you gain the same results for this howto?

**Comment by steveyuwono** [comment]
It is very strange. I obtained the same results for howto 17. I could not find the cause of the problem. Could you share the generated csv file of the training results, either rewards, states or actions?

image
image
image

**Comment by detlefarend** [comment]
Proposal: set a break point in method RLScenario.connect_data_logger(). It switches off/on data logging especially at the beginning/end of an evaluation.

**Comment by steveyuwono** [comment]
I think it should be solved. We should not add any episodes in the RLDataStoring during the evaluation

image
image
image

**Review by steveyuwono — APPROVED** [review]
ok

**Pull request merged**
