### PR TITLE
BF: Multitasking

### PR DESCRIPTION
**Pull request by detlefarend**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by detlefarend** [comment]
Hi colleagues, 

I've reached a first milestone. Classes Range, Shared, Async and first howto bf-mt-001 are implemented/validated. The howto demonstrates the acceleration by multithreading and multiprocessing. Here's a screenshot of my pc's perfmeter:

2022-09-30 MLPro - Multitasking

In single tasking mode just one cpu core is used at a time. In multithreading mode a core per task is partly used. In multiprocessing mode a core per task is fully used...

**Comment by detlefarend** [comment]
If you increase the number of parallel tasks to 50 and decrease their runtime to 0.5 sec then multiprocessing outperforms multithreading drastically:

2022-10-01 MLPro - Multitasking

**Comment by rizkydiprasetya** [comment]
Of course. In multithreading, tasks are executed cocurrently, so the task will be executed a little bit and then it will switch another task and so on. That is why you see only partially used thread. In multiprocessing, the tasks are executed parallely. I dont know how you handle Task in this case, but becareful, dont assign more than the number of your core. Otherwise it will compete each other, and it will execute cocurrently like multithread. Means, it slows down the process.

**Comment by detlefarend** [comment]
Actually, neither a thread nor a process blocks a core for a longer time. A multitasking os has time shift algorithms that assign a core to a process just for a short time slot. We can see this even in synchronous/serial execution on the left. We run a single process with a serial sequence of tasks and the os assigns multiple cores but just one at a time. On the other hand, in multiprocessing mode all cores are used to execute all running processes. We don't really need to care for the number of processes but yes, we can expect a speedup by number of cores and not by number of processes. I actually learned about multithreading that also all cores are involved, but because of Python specific reasons (I guess its the [GIL](https://realpython.com/python-gil/)) not that effective as in multiprocessing. However, it's a very interesting topic and both - multithreading and multiprocessing - have their pros and cons...

**Comment by detlefarend** [comment]
I just pushed my last changes. Howto bf.mt.001 and related RTD section is updated in the branch.

**Comment by rizkydiprasetya** [comment]
Yes of course. But thats not what I meant. I meant how they are executed differently in multithreading and multiprocessing. And it also shown in your graph.

> We don't really need to care for the number of processes but yes, we can expect a speedup by number of cores and not by number of processes.

We need actually. Otherwise as I said, bottleneck is there and you will ended up slowing down, let say, your training. (I have been there).

Yes, GIL is not really helpful in this case.

But I would say, we should mention it on RTD somewhere, when to use multithreading when to use multiprocessing. And shows the different in a graph

**Comment by detlefarend** [comment]
I think the decision for a technique highly depends on several factors and it's hard to give serious recommendations. But to be honest, I don't have experiences here. Just the ones that I could gain by playing around with the howto parameters. However, class Async supports both. There are some hard facts that are important to know: e.g. in multiprocessing you can't access attributes of a shared object directly. You need methods for this - in contrast to multithreading. Furthermore, the current implementation of event handling is limited to multithreading.

**Comment by rizkydiprasetya** [comment]
Thats great. I think it should be enogh for implementation. We can extend more later.

And yes for event, threding will be sufficient.

**Comment by detlefarend** [comment]
Hi colleagues, 

the first implementation of multitasking is done. I added two howtos to demonstrate the main features. In RTD you will find some further annotations and screenshots of my PC's system monitor. Please take a look and let me know what you are thinking. Thank you in advance!

**Review by steveyuwono — APPROVED** [review]

**Pull request merged**
