### PR TITLE
MuJoCo Integration v1

### PR DESCRIPTION
**Pull request by rizkydiprasetya**
## Checklists:

- [x] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [x] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by rizkydiprasetya** [comment]
@steveyuwono @laxmikantbaheti @detlefarend The wrapper is ready to use. Please have a look on it. I want to implement more deep into the simulation design itself. But, we can discuss this on the next meeting.

**Review by detlefarend — COMMENTED** [review]
Hi @rizkydiprasetya, this is definitely a very worthful extension and worth to get the best of it. I see it as the future default systematics for new environments. Here's a little feedback after a brief review:

- Howtos: initial camera position. In howtos 006,007 I see the shadow of the env only. Is it possible to start with a better cam pos?
- Wrapper: param p_visualize currently not supported. It should be possible to turn off the visualization and to use the pure simulation only. To speed up traning/tuning runs, for backend training, ...
- Then an open design task on level rl: EnvBase currently inherits from System and not the wrapper. The question is how to involve the wrapper if I want to use MuJoCo. One way could be to make a generic inheritance in combination with a constant C_SYSTEM_BASE_CLASS. Default is 'System' but a new custom env could override it with the wrapper class. Another possibility could be to really make the wrapper the parent class for EnvBase. The related custom methods (_simulate_reaction, _init_plot_*, _update_plot*,...) can still be redefined if I don't want to use MuJoCo. In that case we should try a late import of MuJoCo on demand to keep MuJoCo optional. Let's discuss this...
- We should also elaborate a good docu in RTD with a step-by-step guide for new envs
- Then a question: does MuJoCo provide functionalities to visualize related data (e.g. trajectory data, state data) - maybe as additional embedded plots? Or arrows for crosswind or other forces or torques?
- A further question about matplotlib integration: is it possible to integrate MuJoCo in a matplotlib figure or alternatively in Tk/Tkinter? 

Let's collect and discuss all ideas and create separate issues for them...

**Comment by rizkydiprasetya** [comment]
@detlefarend 

> Howtos: initial camera position. In howtos 006,007 I see the shadow of the env only. Is it possible to start with a better cam pos?

Possible.

> Wrapper: param p_visualize currently not supported. It should be possible to turn off the visualization and to use the pure simulation only. To speed up traning/tuning runs, for backend training, …

Possible.

> Then an open design task on level rl: EnvBase currently inherits from System and not the wrapper. The question is how to involve the wrapper if I want to use MuJoCo. One way could be to make a generic inheritance in combination with a constant C_SYSTEM_BASE_CLASS. Default is 'System' but a new custom env could override it with the wrapper class. Another possibility could be to really make the wrapper the parent class for EnvBase. The related custom methods (_simulate_reaction, init_plot, _update_plot,...) can still be redefined if I don't want to use MuJoCo. In that case we should try a late import of MuJoCo on demand to keep MuJoCo optional. Let's discuss this…

Next meeting

> We should also elaborate a good docu in RTD with a step-by-step guide for new envs

Ok.

> Then a question: does MuJoCo provide functionalities to visualize related data (e.g. trajectory data, state data) - maybe as additional embedded plots? Or arrows for crosswind or other forces or torques?

Should be possible for embedded plots, need to tweak the openGL. For arrows crosswind and other, I am not sure.

> A further question about matplotlib integration: is it possible to integrate MuJoCo in a matplotlib figure or alternatively in Tk/Tkinter?

Should be possible, need to combine openGL with TKinter. This need to be designed properly with the current sci_ui. Something like this : https://github.com/jonwright/pyopengltk

**Comment by rizkydiprasetya** [comment]
@detlefarend I made the following changes:
- The wrapper can now be used for both Systems and Environment (see Howto_bf_systems_02, Howto_rl_env_006).
- The wrapper can be used also for visualization only (see Howto_rl_env_007).
- For the MuJoCo Visualization, we need to carefully map the state, here I am using the functionality of getting Id by name.
- Due to MuJoCo simulation has its own timestep, we need to synchronise the tilmestep between our algorithm and the simulation. That is why I put now latency even in the C_SIM mode. Please have a look on the changes. Without this, the MuJoCo Simulation will simulate wrong behaviour.

Regarding additional functionality for TKinter, I need more time. For now, I think it should be enough for MuJoCo feature. If something needs to be changed just let me know.

**Comment by rizkydiprasetya** [comment]
Created separate issue for MuJoCo + Tkinter. #573

**Review by detlefarend — COMMENTED** [review]
Hi Rizky, I need a bit more time to fully understand this approach and the consequences. But here's a little feedback in advance...
- Typo in class name MujocoHandler instead of MujocoHanlder
- Howto bf_systems_002: class MyController is not used
- Class WrMujoco: should in my understanding inherit also from System

To be continued...

**Comment by rizkydiprasetya** [comment]
Typo fixed, and MyController is deleted.

In this case, WrMujoco doesnt need to inherit System. It will directly wrap the original object with MuJoCo functionality and return the object itself.

**Comment by rizkydiprasetya** [comment]
@detlefarend I made second approach on #574 .
The different is that: 

In V1, I just remapping all the methods from the original object, and the Wrapper class is used only to check the package compatibility. So at the end it is just the original object with modified method and without inheriting the Wrapper class.

In V2, a new object is created which inherit the Wrapper class.

**Comment by detlefarend** [comment]
@rizkydiprasetya I've spent more time with approach v1 now and of course it works. My concerns are about the consequences for our users (not all of them are Python expert developers). They need to do this extra step of calling the wrapper. What they don't know is the fact that the wrapper reassigns method attributes to completely different code of the wrapper. This is hard to understand and even harder to debug. No one expects that after calling the wrapper a completely different code is called. I really think that this is too advanced and too hard to understand for our average users. The technique of dynamic method reassigment can be helpful to speed up the code or to solve some special issues but in my estimation it should be the last option, not the first. 

My proposal is to follow the origin design and implement the wrapper as a complete and ready-to-use bf.System derivate. That makes it easier for our users to deal with it. I get a complete MuJoCo-based state-based system object with just one call and it uses the code that I expect. 

On the higher rl level I propose to extend class Environment by a new optional parameter p_system : bf.systems.System. If provided then this system is used for everything except rewarding. This means that two steps are necessary to reuse a prepared (MuJoCo) system (instantiate the system, then instantiate the environment) but it keeps the dependency on MuJoCo away from our rl core implementations. Alternatively, a new parameter p_mujoco_file that is internally used to instantiate the wrapper. But then I recommend to implement a dynamic import of MuJoCo on demand instead of a static import. Otherwise one needs always to install MuJoCo to run rl code - even if he/she doesn't need it.

For demonstration/validation we need to separate bf from rl (that's clear). Level bf doesn't know about the higher framework for rl. In consequence we could/should introduce a new pool bf.systems.pool with sample MuJoCo systems. Howto bf.system.002 can refer to one of them without any reference to a higher-level code.
On level rl the lower bf content is known and can be reused. 

Shall we put this topic on the agenda of our next meeting?

**Comment by rizkydiprasetya** [comment]
@detlefarend Which extra step are you talking about? As far as I know, you just need to call the class WrMujoco and that's it. You can see the howto. For special cases, of course you need extra step, because you need to match the naming from mlpro state space and mujoco state space. If you don't want to do the extra step, you need to carefully design the Environment and System from the beginning and match the mujoco model. Please check V2, maybe it is more simpler than this.

> But then I recommend to implement a dynamic import of MuJoCo on demand instead of a static import. Otherwise one needs always to install MuJoCo to run rl code - even if he/she doesn't need it.

why? the import is only from mujoco wrapper, nothing else. 

Yes it is better to put it on the next meeting.

**Comment by detlefarend** [comment]
> @detlefarend Which extra step are you talking about? As far as I know, you just need to call the class WrMujoco and that's it. You can see the howto. For special cases, of course you need extra step, because you need to match the naming from mlpro state space and mujoco state space. If you don't want to do the extra step, you need to carefully design the Environment and System from the beginning and match the mujoco model. Please check V2, maybe it is more simpler than this.
> 
> > But then I recommend to implement a dynamic import of MuJoCo on demand instead of a static import. Otherwise one needs always to install MuJoCo to run rl code - even if he/she doesn't need it.
> 
> why? the import is only from mujoco wrapper, nothing else.
> 
> Yes it is better to put it on the next meeting.

Regarding extra step: I mean line 75 in howto bf. systems.002. In line 71 you instantiate the system. In line 75 you need to call the wrapper that in turn reassigns the method attributes of the origin system. 



Regarding import: if we use the wrapper in rl code we need to import it. The wrapper module in turn imports mujoco. If mujoco is imported on demand if the wrapper is called then it's fine and maybe the better way because it makes it easier to reuse mujoco.

Please check v2 whether it has significant advantages and/or makes it easier for our users to use mujoco in comparison to the origin design that we agreed for (see class diagram for bf.systems). It takes too much time for me to design things and then check alternative implementations that follow a different design. Let's design the things first and agree to a final design. Then, please let's implement it.

**Comment by detlefarend** [comment]
@rizkydiprasetya Gym wrapper is a good example. It says: "hey, I am an MLPro env and I have hidden Gym objects inside". The MuJoCo wrapper says something similar: "I am an MLPro system and I have hidden MuJoCo objects inside". You are right to say that these are two steps: instantiate a MuJoCo object and then wrap it in our wrapper. In the special case of MuJoCo we can make it easier for the user because everything about the MuJoCo system is specified in an xml file.

However, I just notice that we didn't really finalize the integration design together. That's the problem with remote collaboration. It's sometimes better to design central topics together face to face. Let's take some time next Friday to finalize the related class diagrams. Maybe after lunch in R 4.122. Agreed?

**Comment by rizkydiprasetya** [comment]
I see ok, I just followed our previous wrapper design, and the mechanism of it. And yes maybe we can make it easier. Sure we can discuss this on Friday.

**Pull request closed without merging**
