### PR TITLE
BF-Streams: Extensions

### PR DESCRIPTION
**Pull request by detlefarend**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, I implemented class Rearranger. You can run howto_bf_streams_101 to check it. I've already merged it to online_adaptivity10 as well.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti I just turned the pr to draft again due to further extensions. However, it would be nice if you could take a brief look at the Rearranger.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, I implemented a native MLPro stream provider and a first sample stream. See howto_bf_streams_001. I think we better use native streams for our howtos...

**Comment by laxmikantbaheti** [comment]
> Hi @laxmikantbaheti I just turned the pr to draft again due to further extensions. However, it would be nice if you could take a brief look at the Rearranger.

Hi @detlefarend , I took a look at how the rearranger works, and it looks good.

**Comment by laxmikantbaheti** [comment]
> Hi @laxmikantbaheti, I implemented a native MLPro stream provider and a first sample stream. See howto_bf_streams_001. I think we better use native streams for our howtos...

Hi @detlefarend , yes that will be great, also we would be able to avoid the problem of openml in our workflows. 
Currently, the native streams provide random values within given boundaries, right?

**Comment by detlefarend** [comment]
> > Hi @laxmikantbaheti, I implemented a native MLPro stream provider and a first sample stream. See howto_bf_streams_001. I think we better use native streams for our howtos...
> 
> Hi @detlefarend , yes that will be great, also we would be able to avoid the problem of openml in our workflows. Currently, the native streams provide random values within given boundaries, right?

Yes, the first one is a simple 10-dim random pattern. In combination with the Rearranger we can reduce the complexity as needed. 

I also prepared a couple of further streams that generate various patterns like random point clouds (as benchmark for clustering) and other non-random patterns. Here we are completely free and maybe we could also use mp3 audio data for speech/music data and so on. If you have good ideas then feel free to create issues for it.

**Comment by detlefarend** [comment]
... but I need to port them into the new systematics. I'll keep you updated.

**Comment by detlefarend** [comment]
@laxmikantbaheti I refactored our stream howtos a bit. I turned all of them to native MLPro streams to decouple it from OpenML. Furthermore, I implemented the next native stream "Double Spiral 2D". It is used in howto 101 but this is more interesting in 2D view. Then you can see the double spiral...

**Comment by detlefarend** [comment]
I have implemented two further native streams. They generate random instances around 4 center points (2D) respectively 8 center points (3D)...

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, fyi: I implemented plot option 'step rate'.

**Pull request merged**
