### PR TITLE
Simulation of MPPS

### PR DESCRIPTION
**Pull request by steveyuwono**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Review by marlonloeppenberg — COMMENTED** [review]
mpps - add actor motor

**Comment by steveyuwono** [comment]
IMG_1953

**Comment by steveyuwono** [comment]
Here is the recap of the MPPS meeting on 14.10.2022 with @marlonloeppenberg and @detlefarend and the uncompleted tasks from the meeting on 28.09.2022:

1. Transfer Function (from 28.09.2022)
- [ ] Create a howto file
- [ ] Check the plot functionality
- [ ] Complete the function approximation functionality: Linear, Quadratic, BiQuadratic, etc.
- [ ] Move this to MLPro-BF

2. Module and Environment class (from 28.09.2022)
- [ ] Design and construct the classes
- [ ] How to setup components in the module
- [ ] How to setup modules in the environment (serial, serial-parallel, etc.)
- [ ] Sim-MPPS level: Data Storing? Event Trigger? Time management? Hyperparameter initialisation? Action Space? State Space?

3.  Test and validate the Sim-MPPS (from 28.09.2022)
- [ ] Develop an environment as an example
- [ ] Howto file to setup an environment
- [ ] Add objects to the pool: Actuators, Reservoirs, etc.
- [ ] Documentation

4. Prepare a paper (from 28.09.2022)
- [ ] Develop an environment using MPPS and solve it with different approaches: RL, GT, EA, etc.
- [ ] EA Sub-framework?

5.  Integration to hardware control (was CCB-IA), see attachment below.
- [ ] Design and develop MPS class, as discussed, including functionality to switch between Sim-MPPS or hardware control
- [ ] Design and develop CCB-IA-related classes, i.e. ComMQTT, ComOPCUA, Controller, Sensor, Actuator (to be discussed further)
- [ ] How to files
- [ ] Documentation

6. Next meeting
- [ ] 27/10/2022 - Sim-MPPS
- [ ] 18/11/2022 - MPPS in general


Here are the supplementary pictures from the meeting:
IMG_2051
IMG_2052

**Comment by steveyuwono** [comment]
Here are the updates after the MPPS meeting on 27.10.2022:

1. Transfer Function
- [x] Create a howto file
- [x] Check the plot functionality
- [x] Complete the function approximation functionality: Linear, Quadratic, BiQuadratic, etc., future work? Create a separated issue?
- [ ] Remove sine and cosine
- [ ] Function approximation
- [ ] Howto documentation
- [ ] Move this to MLPro-BF

2. Module and Environment class
- [x] Design and construct the module class
- [ ] How to setup components in the module
- [ ] Design and construct the main environment class
- [ ] How to setup modules in the environment (serial, serial-parallel, etc.)
- [ ] Howto documentation
- [ ] Sensor base class
- [ ] Incorporate Sensor to component classes (Reservoir, ManufacturingProcess, etc.)

3.  Test and validate the Sim-MPPS
- [ ] Develop an environment as an example
- [ ] Howto file to setup an environment
- [ ] Howto documentation
- [ ] Add objects to the pool: Actuators, Reservoirs, etc.
- [ ] Documentation

4. Prepare a paper
- [ ] Develop an environment using MPPS and solve it with different approaches: RL, GT, EA, etc.

5.  Integration to hardware control (was CCB-IA), see attachment below.
- [ ] Design and develop MPS class, as discussed, including functionality to switch between Sim-MPPS or hardware control
- [ ] Design and develop CCB-IA-related classes, i.e. ComMQTT, ComOPCUA, Controller, Sensor, Actuator (to be discussed further)
- [ ] How to files
- [ ] Documentation

6. Next meeting
- [ ] 10/11/2022 - Sim-MPPS
- [ ] 18/11/2022 - MPPS in general

**Comment by detlefarend** [comment]
Hi @steveyuwono @marlonloeppenberg, please check whether your MPPS systematics could be black-boxed in a class compatible to mlpro.rl.models_env.AFctSTrans. Such a class could be plugged in to a RL environment (see optional parameter p_afct_strans of class Environment) but to other processes as well. Then a question: do you also provide a systematics for modular reward strategies?

**Comment by steveyuwono** [comment]
> Hi @steveyuwono @marlonloeppenberg, please check whether your MPPS systematics could be black-boxed in a class compatible to mlpro.rl.models_env.AFctSTrans. Such a class could be plugged in to a RL environment (see optional parameter p_afct_strans of class Environment) but to other processes as well. Then a question: do you also provide a systematics for modular reward strategies?

Hi @detlefarend , I believe this might be possible, however, what is the advantage to set them as AFctTrans? At the moment, we will not provide any systematics for the reward strategies or any default implementations.

**Comment by detlefarend** [comment]
The state transition function is actually a more general object in comparison to a rl environment and not limited to rl applications. There was no need up to now but I could imagine a new lower layer for simulation functionalities. Maybe in bf.math or on top of it. I see the advantage in a better and easier reusability of your systematics. At the moment I think that this might be closer to the nature of your work...

**Comment by steveyuwono** [comment]
> The state transition function is actually a more general object in comparison to a rl environment and not limited to rl applications. There was no need up to now but I could imagine a new lower layer for simulation functionalities. Maybe in bf.math or on top of it. I see the advantage in a better and easier reusability of your systematics. At the moment I think that this might be closer to the nature of your work...

It makes sense to have the additional layer to not limited the systematics as the RL environment, especially when we have the hardware control functionality later on. I think it might be possible to set the MPPS as a state transition function. I will consider this after we have decided on the final structure of the MPPS itself.

**Pull request merged**
