### PR TITLE
Callback Function

### PR DESCRIPTION
**Pull request by rizkydiprasetya**
## Checklists:

- [x] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [x] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by rizkydiprasetya** [comment]
@detlefarend @steveyuwono this is done. Check #390 .

**Review by detlefarend — CHANGES_REQUESTED** [review]
Hi Rizky,

you introduced an alternative callback mechanism instead of using event handling. Please check, whether your extensions to the classes scenario/training/rlscenario/rltraining can be solved using event handling. See also howto bf-011. We can also review your extension together in a hackathon.

**Comment by rizkydiprasetya** [comment]
ok

**Comment by rizkydiprasetya** [comment]
@detlefarend done. All the callback stuff are deleted. Re implemented with event handling.

**Review by detlefarend — CHANGES_REQUESTED** [review]
Hi Rizky,

I would like to propose a simplification of your approach: let class Training inherit from bf.events.EventMaanager. Then, define your Events in class Training directly and just raise the events as needed. On the next level RL you can just add further RL-specific events and raise them. Classes MLEventHandler and RLEventHandler are not needed. This is a good preparation of #408 because class Task has an EventManager inside.

Then a question: what is class EventTimer in events.py for? I didn't find a use. If it's needed: let's please check, whether we can inherit from class Task (or more elementary: class Async) Both will support multiprocessing and multithreading as well... The idea of module mp.py is that all classes in MLPro do their asynchronous stuffs by using/inheriting from classes ASync or Task.

Classes Async, Task, Workflow are in progress. I am currently working on it and it will take a while until they are final and stable. Please don't add further async stuffs until this is a) done and b) communicated. Otherwise we just pull MLPro in different directions. 

Last but not least: please take care for line spaces. We agreed to 2 lines between methods and 5 lines between classes. I already cleaned up some modules. That's not the most satisfying work;)

**Comment by rizkydiprasetya** [comment]
> I would like to propose a simplification of your approach: let class Training inherit from bf.events.EventMaanager. Then, define your Events in class Training directly and just raise the events as needed. On the next level RL you can just add further RL-specific events and raise them. Classes MLEventHandler and RLEventHandler are not needed. This is a good preparation of #408 because class Task has an EventManager inside.

Ok.

> Then a question: what is class EventTimer in events.py for? I didn't find a use. If it's needed: let's please check, whether we can inherit from class Task (or more elementary: class Async) Both will support multiprocessing and multithreading as well... The idea of module mp.py is that all classes in MLPro do their asynchronous stuffs by using/inheriting from classes ASync or Task.

It is written there what it is for. And I already prepared Howto for that. Maybe just check it again. I find it use. Maybe not in your implementation. And yes it is related to multi threading.

> Last but not least: please take care for line spaces. We agreed to 2 lines between methods and 5 lines between classes. I already cleaned up some modules. That's not the most satisfying work;)

Habits, dont like too much spaces ;). I write lot of codes, sometimes just forget.

**Comment by detlefarend** [comment]
> > Then a question: what is class EventTimer in events.py for? I didn't find a use. If it's needed: let's please check, whether we can inherit from class Task (or more elementary: class Async) Both will support multiprocessing and multithreading as well... The idea of module mp.py is that all classes in MLPro do their asynchronous stuffs by using/inheriting from classes ASync or Task.
> 
> It is written there what it is for. And I already prepared Howto for that. Maybe just check it again. I find it use. Maybe not in your implementation. And yes it is related to multi threading.

It is definitely a good idea and absolutely useful! I rather meant that I did not find a place in MLPro where it is incorporated. It is more a new multi-purpose tool in our tool box. Because it is about parallel processing I see the class more in bf.mp and it should inherit from Async. But honestly I would really prefer to discuss such conceptual extensions in the team before implementing it. Otherwise we pull MLPro into different directions and loose too much time writing chats.

Here's my proposal: implement the ML/RL event extensions in this branch. For the timer class please add a separate issue. I create a new PR in the next days for multiprocessing (or you create a new one for us both). Then, let's discuss it on Friday in the bigger context of the new classes Async, Shared, Task, Workflow and we implement it in branch bf_multiprocessing. Agreed?

**Comment by rizkydiprasetya** [comment]
> It is definitely a good idea and absolutely useful! I rather meant that I did not find a place in MLPro where it is incorporated. It is more a new multi-purpose tool in our tool box. Because it is about parallel processing I see the class more in bf.mp and it should inherit from Async. But honestly I would really prefer to discuss such conceptual extensions in the team before implementing it. Otherwise we pull MLPro into different directions and loose too much time writing chats.

Discussed weeks ago in Slack. And you said, feel free. So, I implemented those.

> Here's my proposal: implement the ML/RL event extensions in this branch. For the timer class please add a separate issue. I create a new PR in the next days for multiprocessing (or you create a new one for us both). Then, let's discuss it on Friday in the bigger context of the new classes Async, Shared, Task, Workflow and we implement it in branch bf_multiprocessing. Agreed?

Ok.

**Comment by rizkydiprasetya** [comment]
@detlefarend I will close this. Since no point on continuing this before all those functionality that you mentioned are implemented.

**Comment by detlefarend** [comment]
@rizkydiprasetya What about ML/RL event handling? It's independent of multiprocessing.

**Pull request closed without merging**
