### PR TITLE
OA: Online adaptivity12

### PR DESCRIPTION
**Pull request by detlefarend**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti @steveyuwono, I added a switch to turn off the view auto-selection. Howto howto_bf_streams_114_stream_task_deriver.py shows the following:



@steveyuwono I am not sure whether this is plausible...

**Comment by detlefarend** [comment]
@steveyuwono @laxmikantbaheti I also added a new howto_oa_pp_008_rearranger_deriver_normalizer.py. It extends howto_bf_streams_114_stream_task_deriver.py by a boundary detector and min/max normalizer:



This howto processes all 721 instances of the stream. We can see that the input signal is symmetric. Two things are odd: 
- The boundary detector shows asymmetric boundaries for the derived features (@steveyuwono maybe, a problem of the deriver?)
- The normalizer doesn't normalize the features to [-1,1]. I expected all three features in the range [-1,1]. (@laxmikantbaheti maybe, a problem of the normalizer? Or am I wrong?)

**Comment by laxmikantbaheti** [comment]
> @steveyuwono @laxmikantbaheti I also added a new howto_oa_pp_008_rearranger_deriver_normalizer.py. It extends howto_bf_streams_114_stream_task_deriver.py by a boundary detector and min/max normalizer:
> 
> 
> 
> This howto processes all 721 instances of the stream. We can see that the input signal is symmetric. Two things are odd: 
> - The boundary detector shows asymmetric boundaries for the derived features (@steveyuwono maybe, a problem of the deriver?)
> - The normalizer doesn't normalize the features to [-1,1]. I expected all three features in the range [-1,1]. (@laxmikantbaheti maybe, a problem of the normalizer? Or am I wrong?)


Hi, I think maybe it's a bug in BD, I'll check and update you!

**Comment by steveyuwono** [comment]
> 

Hi, thank you for letting us know. I will check this problem later.

**Comment by steveyuwono** [comment]
Hi @laxmikantbaheti @detlefarend , I just shortly checked the howto and found the possible cause of the problem. I think that the boundary detector detects the wrong boundary at the beginning, when the boundaries of all features are still empty.

The first data of the 0. feature is 10, therefore the boundary was detected as [10, 10]. But the first data of the 1. and 2. features are 0, then the boundary was detected as [0, 1]. I added a small if command to adjust with this situation.

I think, it looks correct now. The boundary of the 2. feature is barely seen because it is in between of [-0.012074550185936062, 0.012074550185937838].
image

**Comment by laxmikantbaheti** [comment]
Hi @steveyuwono , thanks for the insight,
Also, there's a bug in renormalization of the plot data, I will try to solve this.

**Comment by steveyuwono** [comment]
> Hi @steveyuwono , thanks for the insight, Also, there's a bug in renormalization of the plot data, I will try to solve this.

No worries. Sorry, which bug do you mean?

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend @steveyuwono , I've found the bug, 
I need to do a small change in normalizers module in bf math.
I will make that in QA 1.0.0 and merge it to OA11.
That's ok right?

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , @steveyuwono , I've fixed the bug. Now the normalization plots are updated correctly at each boundary detection.

**Comment by detlefarend** [comment]
I just checked it. Now it looks plausible. Good job!

**Pull request merged**
