### PR TITLE
BF-ML : Hyperparameter Handling 

### PR DESCRIPTION
**Pull request by laxmikantbaheti**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Comment by laxmikantbaheti** [comment]
Hi everyone, sorry for the multiple pull requests, I was a bit confused, since the actions weren't running. I realized the actions run only on pull the pull requests compared to main. I will keep this one.

**Comment by detlefarend** [comment]
@laxmikantbaheti could you please check the current state of this activity? The related branch is outdated and needs to be updated from main. Can we merge to main afterwards?

**Comment by detlefarend** [comment]
@laxmikantbaheti branch is updated from main...

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , so here the story was to improve the basics of hp tuning. And then in subsequent affected layers, I.e. MLP in SL. So the basics are already implemented. This branch can be safely merged. We can later think of MLP in the sl branch.

Shall I do this?

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, thanks for the update. Yes, please merge to main.

**Pull request merged**
