### PR TITLE
Marketplace for MLPro (11)

### PR DESCRIPTION
**Pull request by detlefarend**

### CODE REVIEW

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend I am currently not able to see the appendix section in the contents tree at the side of the webpage.

**Comment by detlefarend** [comment]
Did you try the right branch? Btw: it is as new main topic "Extension Hub". Can you see the new tiles?

**Comment by laxmikantbaheti** [comment]
> Did you try the right branch? Btw: it is as new main topic "Extension Hub". Can you see the new tiles?

And yes, I can see the new tile, I can access the inner contents, that are a list of organizations and the corresponding extensions

**Comment by detlefarend** [comment]
Did you remove your local folder ./doc/rtd/build in advance?

**Comment by steveyuwono** [comment]
The Extension Hub section can be seen in my RTD. For the moment, it looks good to me!

**Review by steveyuwono — APPROVED** [review]

**Pull request merged**
